[project]
name = "healpix-bigearthnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datetime>=5.5",
    "numpy>=2.3.4",
    "torch>=2.9.1",
]
